import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUserTables1704587669123 implements MigrationInterface {
    name = 'CreateUserTables1704587669123'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "users" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                username text NOT NULL,
                email text NOT NULL,
                "fullName" text NULL,
                "createdAt" timestamptz DEFAULT now() NOT NULL,
                CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id),
                CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE (email),
                CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE (username)
            )
        `);

        await queryRunner.query(`
            CREATE TABLE "access_methods" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                "methodName" text NOT NULL,
                CONSTRAINT "PK_5a10e68060d42a3d0fb86d35ea2" PRIMARY KEY (id),
                CONSTRAINT "UQ_a719e6548d4444da39d0e863ecd" UNIQUE ("methodName")
            )
        `);

        await queryRunner.query(`
            CREATE TABLE "user_types" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                "typeName" text NOT NULL,
                CONSTRAINT "PK_3f05efd7b52a7eca1f6b6f75e45" PRIMARY KEY (id),
                CONSTRAINT "UQ_1d7026294d3d720467c5f5c0c0c" UNIQUE ("typeName")
            )
        `);

        await queryRunner.query(`
            CREATE TABLE "access_history" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                "userId" int8 NOT NULL,
                "accessTime" timestamptz DEFAULT now() NOT NULL,
                "accessMethodId" int8 NOT NULL,
                CONSTRAINT "PK_1fcd54936e03d15fb2474f68922" PRIMARY KEY (id),
                CONSTRAINT "FK_37ca9f60fc769e698dce3da11e2" FOREIGN KEY ("accessMethodId") REFERENCES public.access_methods(id),
                CONSTRAINT "FK_53b3ce0cb5f235d6b11835eff9f" FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE
            )
        `);

        await queryRunner.query(`
            CREATE TABLE "user_credentials" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                "userId" int8 NOT NULL,
                "passwordHash" text NULL,
                "userTypeId" int8 NOT NULL,
                "accessMethodId" int8 NOT NULL,
                "createdAt" timestamptz DEFAULT now() NOT NULL,
                CONSTRAINT "PK_5cadc04d03e2d9fe76e1b44eb34" PRIMARY KEY (id),
                CONSTRAINT "FK_07e09814aad35a2da5ef5a73e14" FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE,
                CONSTRAINT "FK_2f8bf4a6fb87cf593cea283e7d5" FOREIGN KEY ("userTypeId") REFERENCES public.user_types(id),
                CONSTRAINT "FK_cef6a8cadb3a2cb31f40d4eaa32" FOREIGN KEY ("accessMethodId") REFERENCES public.access_methods(id)
            )
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TABLE "user_credentials"
        `);
        await queryRunner.query(`
            DROP TABLE "access_history"
        `);
        await queryRunner.query(`
            DROP TABLE "user_types"
        `);
        await queryRunner.query(`
            DROP TABLE "access_methods"
        `);
        await queryRunner.query(`
            DROP TABLE "users"
        `);
    }
}