import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateActionLogsTable1729612800000 implements MigrationInterface {
    name = 'CreateActionLogsTable1729612800000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "action_logs" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                action text NOT NULL,
                "textDescription" text NOT NULL,
                "userId" int8 NOT NULL,
                endpoint text NOT NULL,
                method text NOT NULL,
                "createdAt" timestamptz DEFAULT now() NOT NULL,
                CONSTRAINT "PK_action_logs_id" PRIMARY KEY (id),
                CONSTRAINT "FK_action_logs_user" FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE
            )
        `);

        await queryRunner.query(`
            CREATE INDEX "IDX_action_logs_user_id" ON "action_logs" ("userId")
        `);

        await queryRunner.query(`
            CREATE INDEX "IDX_action_logs_action" ON "action_logs" (action)
        `);

        await queryRunner.query(`
            CREATE INDEX "IDX_action_logs_created_at" ON "action_logs" ("createdAt")
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP INDEX "IDX_action_logs_created_at"
        `);
        await queryRunner.query(`
            DROP INDEX "IDX_action_logs_action"
        `);
        await queryRunner.query(`
            DROP INDEX "IDX_action_logs_user_id"
        `);
        await queryRunner.query(`
            DROP TABLE "action_logs"
        `);
    }
}
