import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateBannerImagesTable1729700000000 implements MigrationInterface {
    name = 'CreateBannerImagesTable1729700000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "banner_images" (
                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                "imageUrl" text NOT NULL,
                "originalName" text NOT NULL,
                "displayOrder" int4 NULL,
                "isActive" boolean DEFAULT false NOT NULL,
                "uploadedBy" int8 NOT NULL,
                "createdAt" timestamptz DEFAULT now() NOT NULL,
                "updatedAt" timestamptz DEFAULT now() NOT NULL,
                CONSTRAINT "PK_banner_images_id" PRIMARY KEY (id),
                CONSTRAINT "FK_banner_images_uploaded_by" FOREIGN KEY ("uploadedBy") REFERENCES public.users(id) ON DELETE CASCADE,
                CONSTRAINT "CHK_display_order_range" CHECK ("displayOrder" IS NULL OR ("displayOrder" >= 1 AND "displayOrder" <= 4)),
                CONSTRAINT "UQ_display_order" UNIQUE ("displayOrder")
            )
        `);

        await queryRunner.query(`
            CREATE INDEX "IDX_banner_images_is_active" ON "banner_images" ("isActive")
        `);

        await queryRunner.query(`
            CREATE INDEX "IDX_banner_images_display_order" ON "banner_images" ("displayOrder")
        `);

        await queryRunner.query(`
            CREATE INDEX "IDX_banner_images_uploaded_by" ON "banner_images" ("uploadedBy")
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP INDEX "IDX_banner_images_uploaded_by"
        `);
        await queryRunner.query(`
            DROP INDEX "IDX_banner_images_display_order"
        `);
        await queryRunner.query(`
            DROP INDEX "IDX_banner_images_is_active"
        `);
        await queryRunner.query(`
            DROP TABLE "banner_images"
        `);
    }
}
